import { z } from 'zod';
export const kinds = ['chapter','character','clue','idea','note'] as const;
export type Kind = typeof kinds[number];
export const labels: Record<Kind,string> = {chapter:'章节',character:'人物',clue:'伏笔',idea:'脑洞',note:'便签'};
export const statuses: Record<Kind,string[]> = {chapter:['候选','已定','已写','待修'],character:['待完善','已定'],clue:['待埋','已埋','已回收'],idea:['暂存','待验证','采用','留给下本'],note:['随记','已定']};
export const colors = ['#6588ce','#4f9e91','#d77890','#d3a546','#9677bd','#8793a3'];
const id = z.string().min(1).max(100), short = z.string().max(500), long = z.string().max(100000);
export const StageSchema = z.object({id,title:short,goal:long,start:long,end:long,turn:long,bridge:long,boundary:long,locked:z.boolean()});
export const CardSchema = z.object({id,kind:z.enum(kinds),title:short,text:long,body:long,revisionNotes:long,stageId:z.string().max(100),order:z.number().finite(),x:z.number().finite().min(-50000).max(50000),y:z.number().finite().min(-50000).max(50000),color:z.string().regex(/^#[a-fA-F0-9]{6}$/),status:short,pinned:z.boolean(),fields:z.record(z.string().max(100),long),tags:z.array(z.string().max(80)).max(30),characterIds:z.array(id).max(100).default([]),deletedAt:z.string().nullable(),updatedAt:z.string()});
export const LinkSchema = z.object({id,from:id,to:id,label:short,color:z.string().regex(/^#[a-fA-F0-9]{6}$/).default('#7890b1'),style:z.enum(['curve','straight','elbow']).default('curve'),dash:z.enum(['solid','dash','dot']).default('solid'),arrow:z.enum(['filled','open','none']).default('filled'),size:z.number().min(8).max(32).default(16),width:z.number().min(1).max(5).default(2)});
export const BookSchema = z.object({id,title:short,promise:long,ending:long,demo:z.boolean(),stages:z.array(StageSchema).max(80),cards:z.array(CardSchema).max(1500),links:z.array(LinkSchema).max(3000)});
export const WorkspaceSchema = z.object({schemaVersion:z.literal(1),books:z.array(BookSchema).min(1).max(30)}).superRefine((w,ctx)=>{const ids=new Set<string>();for(const b of w.books){for(const x of [b,...b.stages,...b.cards,...b.links]){if(ids.has(x.id))ctx.addIssue({code:'custom',message:'重复编号'});ids.add(x.id);}const cs=new Set(b.cards.map(c=>c.id));const ss=new Set(b.stages.map(s=>s.id));for(const c of b.cards){if(c.stageId&&!ss.has(c.stageId))ctx.addIssue({code:'custom',message:'阶段不存在'});}for(const l of b.links)if(!cs.has(l.from)||!cs.has(l.to)||l.from===l.to)ctx.addIssue({code:'custom',message:'无效关联'});}});
export type Card=z.infer<typeof CardSchema>;export type Book=z.infer<typeof BookSchema>;export type Stage=z.infer<typeof StageSchema>;export type Link=z.infer<typeof LinkSchema>;export type Workspace=z.infer<typeof WorkspaceSchema>;
export const uid=()=>crypto.randomUUID();
export const makeStage=(title='新阶段'):Stage=>({id:uid(),title,goal:'',start:'',end:'',turn:'',bridge:'',boundary:'',locked:false});
export const makeCard=(kind:Kind,index=0):Card=>({id:uid(),kind,title:'',text:'',body:'',revisionNotes:'',stageId:'',order:index,x:70+(index%3)*350,y:65+Math.floor(index/3)*310,color:colors[kinds.indexOf(kind)],status:statuses[kind][0],pinned:false,fields:{},tags:[],characterIds:[],deletedAt:null,updatedAt:new Date().toISOString()});
export const makeBook=(title='我的小说'):Book=>({id:uid(),title,promise:'',ending:'',demo:false,stages:[makeStage('开篇 · 事情开始失控'),makeStage('发展 · 选择带来代价'),makeStage('终局 · 兑现变化')],cards:[],links:[]});
export function chaptersOf(b:Book){return b.cards.filter(c=>!c.deletedAt&&c.kind==='chapter').sort((a,c)=>{const phase=(x:Card)=>{const n=b.stages.findIndex(s=>s.id===x.stageId);return n<0?b.stages.length:n;};return phase(a)-phase(c)||a.order-c.order;});}
export function moveChapter(b:Book,id:string,stageId:string,before?:string){const card=b.cards.find(c=>c.id===id);if(!card)return;const list=chaptersOf(b).filter(c=>c.id!==id&&c.stageId===stageId);const idx=list.findIndex(c=>c.id===before);list.splice(idx<0?list.length:idx,0,card);list.forEach((c,i)=>{c.stageId=stageId;c.order=i;});}
export function cloneBook(b:Book,title=b.title+' · 副本'):Book{const copy=structuredClone(b),map=new Map<string,string>();for(const x of [copy,...copy.cards,...copy.stages,...copy.links]){map.set(x.id,uid());}copy.id=map.get(copy.id)!;copy.title=title;copy.demo=false;copy.stages.forEach(s=>s.id=map.get(s.id)!);copy.cards.forEach(c=>{c.id=map.get(c.id)!;c.stageId=map.get(c.stageId)||'';c.characterIds=c.characterIds.map(x=>map.get(x)).filter((x):x is string=>!!x);for(const key of ['plantCard','plannedCard','payoffCard'])if(c.fields[key])c.fields[key]=map.get(c.fields[key])||'';});copy.links.forEach(l=>{l.id=map.get(l.id)!;l.from=map.get(l.from)!;l.to=map.get(l.to)!;});return copy;}
export function seedWorkspace():Workspace{const b=makeBook('旧书店的两天');b.demo=true;b.promise='一家即将关门的旧书店，一张没有署名的借书条。';b.ending='林遥终于决定留下自己的故事。';const a=makeCard('chapter',0),c=makeCard('chapter',1),d=makeCard('chapter',2),person=makeCard('character',3),clue=makeCard('clue',4),idea=makeCard('idea',5);a.title='停业通知';a.text='林遥回到旧书店收拾遗物，却发现最后一位客人留下了一张借书条。';a.fields={goal:'两天内清空书店。',choice:'借书条让她决定再等一晚。',result:'清空计划被打断，她第一次主动追问父亲的过去。'};c.title='失踪的那一页';c.text='她找到借书记录，却发现关键的一页被撕掉；邻居的回避让她怀疑这并非偶然。';d.title='把灯留下';d.text='期限到了。她需要在按时交出钥匙和等待一个答案之间做出选择。';[a,c,d].forEach((x,i)=>{x.stageId=b.stages[0].id;x.order=i;});a.status='已定';person.title='林遥';person.text='28 岁，习惯把情绪写进待办事项。';person.fields={goal:'尽快处理完父亲的书店',fear:'害怕自己从未真正了解父亲',change:'从结束一件事，到愿意理解一个人'};[a,c,d].forEach(x=>x.characterIds=[person.id]);clue.title='没有署名的借书条';clue.text='借阅日期被划掉，背面写着一句“下次再还”。';clue.fields={plantCard:a.id,plannedCard:d.id,truth:'借书的人每年都在同一天来。'};clue.status='已埋';idea.title='如果最后一位客人没有来？';idea.text='先留在这里。等写到第三章，再判断这个缺席是否让结尾更有力量。';b.cards=[a,c,d,person,clue,idea];b.links=[LinkSchema.parse({id:uid(),from:a.id,to:c.id,label:'追问',color:'#6588ce'}),LinkSchema.parse({id:uid(),from:c.id,to:d.id,label:'做出选择',color:'#6588ce'}),LinkSchema.parse({id:uid(),from:clue.id,to:d.id,label:'计划回收',color:'#d77890',dash:'dash'})];return{schemaVersion:1,books:[b,makeBook()]};}
export const fieldNames:Record<string,string>={goal:'承接与目标',choice:'阻力与人物选择',event:'事件落地',result:'结果 / 代价',pov:'视角',emotion:'情绪变化',relation:'关系变化',hook:'章末牵引',detail:'关键细节',fear:'恐惧与弱点',need:'真正需要',habit:'言行习惯',change:'人物变化',truth:'真实含义',surface:'读者最初理解',evidence:'回收落点'};
export const wordCount=(s:string)=>Array.from(s.replace(/\s/g,'')).length;
export function markdown(b:Book){const nums=new Map(chaptersOf(b).map((c,i)=>[c.id,i+1]));let s=`# ${b.title}\n\n${b.promise}\n\n预想终点：${b.ending}\n`;for(const stage of [...b.stages,{id:'',title:'未分阶段',goal:'',start:'',end:'',turn:'',bridge:'',boundary:''}]){s+=`\n## ${stage.title}\n`;for(const k of ['goal','start','end','turn','bridge','boundary'] as const)if(stage[k])s+=`\n${({goal:'阶段目标',start:'起点状态',end:'终点状态',turn:'关键转折',bridge:'阶段衔接',boundary:'暂不展开'})[k]}：${stage[k]}\n`;for(const c of chaptersOf(b).filter(c=>c.stageId===stage.id))s+=print(c,`第 ${nums.get(c.id)} 章 · `);}for(const kind of kinds.filter(k=>k!=='chapter')){s+=`\n## ${labels[kind]}\n`;for(const c of b.cards.filter(c=>!c.deletedAt&&c.kind===kind))s+=print(c,'');}return s;function print(c:Card,prefix:string){return`\n### ${prefix}${c.title||'未命名'}\n\n${c.text}\n`+Object.entries(c.fields).filter(([,v])=>v).map(([k,v])=>`\n${fieldNames[k]||({plantCard:'埋设章节',plannedCard:'计划回收',payoffCard:'实际回收'} as Record<string,string>)[k]||k}：${k.endsWith('Card')?(b.cards.find(x=>x.id===v)?.title||'已移除章节'):v}\n`).join('')+(c.characterIds.length?`\n出场人物：${c.characterIds.map(id=>b.cards.find(x=>x.id===id)?.title).filter(Boolean).join('、')}\n`:'')+(c.body?`\n正文：\n\n${c.body}\n`:'')+(c.revisionNotes?`\n修文记录：\n${c.revisionNotes}\n`:'');}}
